name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history

    - name: Debug - Verify checkout
      run: |
        echo "Current directory: $(pwd)"
        echo "Files checked out:"
        ls -la
        echo "Looking for package.json:"
        find . -name "package.json" -type f | grep -v "_tool" | grep -v "_actions" || echo "No project package.json found"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
         cache-dependency-path: '**/package-lock.json'

    - name: Install dependencies
      run: |
        # Check if package.json exists in current directory
        if [ -f "package.json" ]; then
          echo "Found package.json in current directory"
          npm ci  # Use ci for cleaner installs with lock file
        else
          # Search for package.json in any subdirectory
          PACKAGE_DIR=$(find . -name "package.json" -type f -printf '%h\n' | head -1)
          if [ -n "$PACKAGE_DIR" ]; then
            echo "Found package.json in subdirectory: $PACKAGE_DIR"
            cd "$PACKAGE_DIR"
            npm ci
          else
            echo "ERROR: No package.json found anywhere!"
            echo "Searching all files:"
            find . -type f -name "*" | head -20
            exit 1
          fi
        fi

    - name: Build
      run: npm run build --if-present

    - name: Test
      run: npm test --if-present
