name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history

    - name: Debug - Verify checkout
      run: |
        echo "Current directory: $(pwd)"
        echo "Files checked out:"
        ls -la
        echo "Looking for package.json:"
        find . -name "package.json" -type f | grep -v "_tool" | grep -v "_actions" || echo "No project package.json found"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
         

    - name: Install dependencies
      run: npm ci
         

  
